name: GitHub Action for pylint
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: GitHub Action for pylint
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: cclauss/GitHub-Action-for-pylint@0.7.0
    - run: pip install --upgrade pip
    - run: pip install pylint==v3.0.0a3
    - run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
